# Generated by Django 3.1.5 on 2024-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_auto_20240315_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
