# Generated by Django 3.1.5 on 2024-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_auto_20240315_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
